=== andresfp16/andresfp16.github.io/temas/tema7/examenxml/Ejercicio3/ejercicio3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="series">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="serie" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" maxOccurs="unbounded" minOccurs="1" type="xs:string"></xs:element>
                            <xs:element name="nacionalidad" maxOccurs="1" minOccurs="1" type="xs:string"></xs:element>
                            <xs:element name="genero" maxOccurs="unbounded" minOccurs="1" type="xs:string"></xs:element>
                            <xs:element name="clasificacion" maxOccurs="1" minOccurs="1">
                                <xs:complexType>
                                    <xs:attribute name="edad">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="tp"></xs:enumeration>
                                                <xs:enumeration value="8"></xs:enumeration>
                                                <xs:enumeration value="12"></xs:enumeration>
                                                <xs:enumeration value="16"></xs:enumeration>
                                                <xs:enumeration value="18"></xs:enumeration>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="web_oficial" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
                            <xs:element name="sinopsis" maxOccurs="1" minOccurs="1" type="xs:string"></xs:element>
                            <xs:element name="director" maxOccurs="1" minOccurs="1" type="xs:string"></xs:element>
                            <xs:element name="reparto" maxOccurs="1" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="actor" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="enlace_imdb" minOccurs="0" maxOccurs="1" type="xs:string"></xs:element>
                            <xs:element name="cartel" minOccurs="0" maxOccurs="unbounded" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="codigo" type="xs:ID"></xs:attribute>
                        <xs:attribute name="temporadas" type="xs:positiveInteger" default="1"></xs:attribute>
                        <xs:attribute name="aÃ±o" type="xs:gYear"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== andresfp16/andresfp16.github.io/temas/tema7/examenxml/Ejercicio3/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<series xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation="ejercicio3.xsd">
    <serie codigo="c1" temporadas="1" año="2021">
        <titulo>the rooftop series</titulo>
        <nacionalidad>Estados Unidos</nacionalidad>
        <genero>Música</genero>
        <clasificacion edad="tp"/>
        <web_oficial>http://www.rooftop.com</web_oficial>
        <sinopsis>
            The Rooftop Series is a curated place to find new music and
            artists before they hit the mainstream.
        </sinopsis>
        <director>Madison McIntyre </director>
        <reparto>
            <actor>Blair West </actor>
            <actor>Cade Hoppe</actor>
        </reparto>
        <enlace_imdb>http://www.uip.es</enlace_imdb>
        <cartel>c1.jpg</cartel>
    </serie>   
    
    <serie codigo="c2" temporadas="1" año="2021">
        <titulo>the rooftop series</titulo>
        <nacionalidad>Estados Unidos</nacionalidad>
        <genero>Música</genero>
        <clasificacion edad="12"/>
        <web_oficial>http://www.rooftop.com</web_oficial>
        <sinopsis>
            The Rooftop Series is a curated place to find new music and
            artists before they hit the mainstream.
        </sinopsis>
        <director>Madison McIntyre </director>
        <reparto>
            <actor>Blair West </actor>
        </reparto>
    </serie>    

</series>
