<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deportistas [

<!ELEMENT deportistas (deportista*)>
<!ELEMENT deporte (#PCDATA)>
<!ELEMENT deportista (deporte, nombre)>
<!ELEMENT nombre (#PCDATA)>

]>
<deportistas>
  <deportista>
    <deporte> Atletismo </deporte>
    <nombre>Jesse Owens</nombre>
   </deportista>

  <deportista>
    <deporte> Nataci√≥n </deporte>
    <nombre>Mark Spitz</nombre>
  </deportista>
</deportistas>