=== andresfp16/andresfp16.github.io/temas/tema7/examenxml/Ejercicio1/Cordofly.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cordofly">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="aviones" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="avion" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="modelo" minOccurs="1" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Airbus A319"/>
                                                    <xs:enumeration value="Airbus A320"/>
                                                    <xs:enumeration value="Boeing 747"/>
                                                    <xs:enumeration value="Boeing 777"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="numpasajeros" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                    <xs:minExclusive value="50"/>

                                                    <xs:maxInclusive value="300"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        
                                    </xs:sequence>
                                    <xs:attribute name="cod" type="xs:ID"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="aeropuertos" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="aeropuerto" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ciudad" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                        <xs:element name="pais" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                    </xs:sequence>
                                    <xs:attribute name="cod" type="xs:ID"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="rutas" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ruta" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="aeropuertosruta" maxOccurs="1" minOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="aeropuertosalida" maxOccurs="1" minOccurs="1" type="xs:string"/>
                                                    <xs:element name="aeropuertollegada" maxOccurs="1" minOccurs="1" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="numvuelo" maxOccurs="1" minOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z][A-Z][0-9][0-9][0-9][0-9]"></xs:pattern>

                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        
                                        <xs:element name="horas" maxOccurs="1" minOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="despegue" maxOccurs="1" minOccurs="1" type="xs:string"/>
                                                    <xs:element name="aterrizaje" maxOccurs="1" minOccurs="1" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="avionutilizado" minOccurs="1" maxOccurs="1" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="cod" type="xs:ID"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== andresfp16/andresfp16.github.io/temas/tema7/examenxml/Ejercicio1/CordoFly.xml
<?xml version="1.0" encoding="UTF-8"?>
<cordofly xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xsi:noNamespaceSchemaLocation="Cordofly.xsd">
    <aviones>
        <avion cod="Avion1">
            <modelo>Airbus A319</modelo>
            <numpasajeros>126</numpasajeros>
        </avion>
    </aviones>
    <aeropuertos>
        <aeropuerto cod="AeroPuerto1">
            <ciudad>
                Malaga
            </ciudad>
            <pais>
                Espa√±a
            </pais>
        </aeropuerto>
        <aeropuerto cod="AeroPuerto2">
            <ciudad>
                Londres
            </ciudad>
            <pais>
                ReinoUnido
            </pais>
        </aeropuerto>
    </aeropuertos>
    <rutas>
        <ruta cod="Ruta1">
            <aeropuertosruta>
                <aeropuertosalida>
                    AeroPuerto1
                </aeropuertosalida>
                <aeropuertollegada>
                    AeroPuerto2
                </aeropuertollegada>
            </aeropuertosruta>

            <numvuelo>MA0316</numvuelo>
            <horas>
                <despegue>
                    15:00
                </despegue>
                <aterrizaje>
                    17:15
                </aterrizaje>
            </horas>
            <avionutilizado>
                Avion1
            </avionutilizado>
        </ruta>
    </rutas>
</cordofly>
